import { Badge } from '@/components/ui';
import {
  ResponsiveContainer,
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip as RTooltip,
  BarChart,
  Bar,
  Cell,
} from 'recharts';
import { ANALYTICS_KPIS, TRANSFORMATIONS_OVER_TIME, OUTPUT_USAGE, SOURCE_DISTRIBUTION, CHART_COLORS } from '@/data/analytics';
import { SOURCE_KIND_META } from '@/components/common';
import { Card, CardHeader } from '@/components/ui';

export function Analytics() {
  return (
    <div className="space-y-6">
      {/* KPI cards */}
      <section aria-label="Analytics summary" className="grid grid-cols-2 gap-4 xl:grid-cols-4">
        {ANALYTICS_KPIS.map((kpi) => (
          <Card key={kpi.id} className="p-4">
            <p className="text-xs font-medium text-slate-400">{kpi.label}</p>
            <p className="mt-2 text-3xl font-bold tracking-tight text-slate-50">{kpi.value}</p>
          </Card>
        ))}
      </section>

      {/* Transformations over time */}
      <Card>
        <CardHeader
          title="Transformations over time"
          subtitle="Monthly volume of transformations and generated outputs."
          actions={<Badge tone="accent">6 months</Badge>}
        />
        <div className="h-64 px-3 pb-4">
          <ResponsiveContainer width="100%" height="100%">
            <AreaChart data={TRANSFORMATIONS_OVER_TIME} margin={{ top: 8, right: 16, left: -14, bottom: 0 }}>
              <defs>
                <linearGradient id="gradTransformations" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="0%" stopColor={CHART_COLORS.cyan} stopOpacity={0.35} />
                  <stop offset="100%" stopColor={CHART_COLORS.cyan} stopOpacity={0} />
                </linearGradient>
                <linearGradient id="gradOutputs" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="0%" stopColor={CHART_COLORS.blue} stopOpacity={0.25} />
                  <stop offset="100%" stopColor={CHART_COLORS.blue} stopOpacity={0} />
                </linearGradient>
              </defs>
              <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" vertical={false} />
              <XAxis dataKey="month" tick={{ fill: '#64748b', fontSize: 11 }} axisLine={{ stroke: '#1e293b' }} tickLine={false} />
              <YAxis tick={{ fill: '#64748b', fontSize: 11 }} axisLine={false} tickLine={false} />
              <RTooltip
                contentStyle={{
                  background: '#0e1524',
                  border: '1px solid #223050',
                  borderRadius: 8,
                  fontSize: 12,
                  color: '#e2e8f0',
                }}
              />
              <Area type="monotone" dataKey="outputs" name="Outputs" stroke={CHART_COLORS.blue} strokeWidth={1.5} fill="url(#gradOutputs)" />
              <Area type="monotone" dataKey="transformations" name="Transformations" stroke={CHART_COLORS.cyan} strokeWidth={2} fill="url(#gradTransformations)" />
            </AreaChart>
          </ResponsiveContainer>
        </div>
      </Card>

      <div className="grid grid-cols-1 gap-6 xl:grid-cols-2">
        {/* Output usage */}
        <Card>
          <CardHeader title="Output type usage" subtitle="Deliverables generated by type (all time)." />
          <div className="h-64 px-3 pb-4">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={OUTPUT_USAGE} layout="vertical" margin={{ top: 4, right: 24, left: 8, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" horizontal={false} />
                <XAxis type="number" tick={{ fill: '#64748b', fontSize: 11 }} axisLine={false} tickLine={false} />
                <YAxis
                  type="category"
                  dataKey="name"
                  width={110}
                  tick={{ fill: '#94a3b8', fontSize: 11 }}
                  axisLine={false}
                  tickLine={false}
                />
                <RTooltip
                  cursor={{ fill: 'rgba(148,163,184,0.06)' }}
                  contentStyle={{ background: '#0e1524', border: '1px solid #223050', borderRadius: 8, fontSize: 12, color: '#e2e8f0' }}
                />
                <Bar dataKey="count" name="Deliverables" radius={[0, 4, 4, 0]} barSize={14}>
                  {OUTPUT_USAGE.map((entry, i) => (
                    <Cell key={entry.kind} fill={i === 0 ? CHART_COLORS.cyan : CHART_COLORS.blue} fillOpacity={i === 0 ? 0.95 : 0.55 + (0.05 * i)} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </Card>

        {/* Source distribution */}
        <Card>
          <CardHeader title="Source type distribution" subtitle="Which input kinds operators transform most." />
          <div className="h-64 px-3 pb-4">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={SOURCE_DISTRIBUTION} margin={{ top: 4, right: 16, left: -18, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" vertical={false} />
                <XAxis dataKey="name" tick={{ fill: '#94a3b8', fontSize: 11 }} axisLine={{ stroke: '#1e293b' }} tickLine={false} />
                <YAxis tick={{ fill: '#64748b', fontSize: 11 }} axisLine={false} tickLine={false} />
                <RTooltip
                  cursor={{ fill: 'rgba(148,163,184,0.06)' }}
                  contentStyle={{ background: '#0e1524', border: '1px solid #223050', borderRadius: 8, fontSize: 12, color: '#e2e8f0' }}
                />
                <Bar dataKey="count" name="Sources" radius={[4, 4, 0, 0]} barSize={28}>
                  {SOURCE_DISTRIBUTION.map((entry, i) => (
                    <Cell key={entry.kind} fill={i === 0 ? CHART_COLORS.cyan : CHART_COLORS.slate} fillOpacity={i === 0 ? 0.95 : 0.6} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
          {/* Compact legend with real icons */}
          <div className="flex flex-wrap gap-3 border-t border-ink-700/50 px-5 py-3">
            {SOURCE_DISTRIBUTION.map((s) => {
              const { icon: Icon, label } = SOURCE_KIND_META[s.kind];
              return (
                <span key={s.kind} className="inline-flex items-center gap-1.5 text-[11px] text-slate-400">
                  <Icon aria-hidden className="h-3.5 w-3.5 text-accent-400" />
                  {label} · {s.count}
                </span>
              );
            })}
          </div>
        </Card>
      </div>
    </div>
  );
}

