"""initial schema: sources, transformations, generation_configurations, outputs

Revision ID: 7a3746be8eb7
Revises: 
Create Date: 2026-09-29 13:42:24.857965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7a3746be8eb7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('TEXT', 'DOCUMENT', 'IMAGE', 'VIDEO', 'URL', name='source_type', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=127), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    op.create_table('transformations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'PROCESSING', 'COMPLETED', 'FAILED', name='transformation_status', native_enum=False, length=32), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_transformations_source_id_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transformations'))
    )
    op.create_index(op.f('ix_transformations_source_id'), 'transformations', ['source_id'], unique=False)
    op.create_table('generation_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transformation_id', sa.Integer(), nullable=False),
    sa.Column('target_audience', sa.Enum('GENERAL_PUBLIC', 'TECHNICAL_TEAM', 'EXECUTIVES', 'GOVERNMENT_OFFICIALS', 'SECURITY_OFFICERS', name='target_audience', native_enum=False, length=64), nullable=False),
    sa.Column('tone', sa.Enum('PROFESSIONAL', 'FORMAL', 'TECHNICAL', 'INFORMATIVE', 'URGENT', name='tone', native_enum=False, length=32), nullable=False),
    sa.Column('language', sa.Enum('ENGLISH', 'HINDI', 'TELUGU', name='language', native_enum=False, length=32), nullable=False),
    sa.Column('detail_level', sa.Enum('BRIEF', 'STANDARD', 'DETAILED', name='detail_level', native_enum=False, length=32), nullable=False),
    sa.Column('communication_objective', sa.Enum('INFORM', 'ALERT', 'EDUCATE', 'BRIEF', 'PUBLISH', name='communication_objective', native_enum=False, length=32), nullable=False),
    sa.Column('content_style', sa.Enum('REPORT', 'ADVISORY', 'CORPORATE', 'SOCIAL', 'PRESENTATION', name='content_style', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['transformation_id'], ['transformations.id'], name=op.f('fk_generation_configurations_transformation_id_transformations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_configurations'))
    )
    op.create_index(op.f('ix_generation_configurations_transformation_id'), 'generation_configurations', ['transformation_id'], unique=True)
    op.create_table('outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transformation_id', sa.Integer(), nullable=False),
    sa.Column('output_type', sa.Enum('ADVISORY', 'EXECUTIVE_SUMMARY', 'LINKEDIN', 'X_POST', 'PRESENTATION', 'INFOGRAPHIC', 'VIDEO_PACKAGE', name='output_type', native_enum=False, length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='output_status', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['transformation_id'], ['transformations.id'], name=op.f('fk_outputs_transformation_id_transformations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outputs'))
    )
    op.create_index(op.f('ix_outputs_transformation_id'), 'outputs', ['transformation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outputs_transformation_id'), table_name='outputs')
    op.drop_table('outputs')
    op.drop_index(op.f('ix_generation_configurations_transformation_id'), table_name='generation_configurations')
    op.drop_table('generation_configurations')
    op.drop_index(op.f('ix_transformations_source_id'), table_name='transformations')
    op.drop_table('transformations')
    op.drop_table('sources')
    # ### end Alembic commands ###
