"""add sources.processor_metadata for extraction details

Revision ID: c13052d82f40
Revises: 7a3746be8eb7
Create Date: 2026-09-29 14:25:53.430924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c13052d82f40'
down_revision: Union[str, None] = '7a3746be8eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('processor_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'processor_metadata')
    # ### end Alembic commands ###
